version: "3.9"

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: flask-app:latest
    container_name: flask-app
    ports:
      - 5000:5000
    environment:
      - APP_NAME=FlaskApp
    
