version: "3.9"

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: flask-app:latest
    container_name: flask-app
    networks:
      - net-gateway
    ports:
      - 5000:5000
    volumes:
      - /home/superman/dockerVolume/flaskapp:/app/databases:rw
    environment:
      - APP_NAME=FlaskApp
    
